// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhTiEOi-VGkeI-LQntCfBj2_ZkHJHmevA',
    appId: '1:925355269264:android:8ed91d4f65cc8053048c15',
    messagingSenderId: '925355269264',
    projectId: 'chairty-app-3dd34',
    storageBucket: 'chairty-app-3dd34.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2M6TSc94jWqBqf4vYQ9ZLj2pdfDzDFNU',
    appId: '1:925355269264:web:6df642081e729f1e048c15',
    messagingSenderId: '925355269264',
    projectId: 'chairty-app-3dd34',
    authDomain: 'chairty-app-3dd34.firebaseapp.com',
    storageBucket: 'chairty-app-3dd34.firebasestorage.app',
    measurementId: 'G-ZZEVZMRQRN',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2M6TSc94jWqBqf4vYQ9ZLj2pdfDzDFNU',
    appId: '1:925355269264:web:6df642081e729f1e048c15',
    messagingSenderId: '925355269264',
    projectId: 'chairty-app-3dd34',
    authDomain: 'chairty-app-3dd34.firebaseapp.com',
    storageBucket: 'chairty-app-3dd34.firebasestorage.app',
    measurementId: 'G-ZZEVZMRQRN',
  );
}
